services:
  - type: web
    name: leave-manager
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:/opt/render/project/data/prod.db
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/data
      sizeGB: 1
